<?php return array(
    4   => array('id' => 4  , 'alpha2' => 'AF', 'alpha3' => 'AFG', 'name' => 'Afghanistan'),
    248 => array('id' => 248, 'alpha2' => 'AX', 'alpha3' => 'ALA', 'name' => 'Åland Islands'),
    8   => array('id' => 8  , 'alpha2' => 'AL', 'alpha3' => 'ALB', 'name' => 'Albania'),
    12  => array('id' => 12 , 'alpha2' => 'DZ', 'alpha3' => 'DZA', 'name' => 'Algeria'),
    16  => array('id' => 16 , 'alpha2' => 'AS', 'alpha3' => 'ASM', 'name' => 'American Samoa'),
    20  => array('id' => 20 , 'alpha2' => 'AD', 'alpha3' => 'AND', 'name' => 'Andorra'),
    24  => array('id' => 24 , 'alpha2' => 'AO', 'alpha3' => 'AGO', 'name' => 'Angola'),
    660 => array('id' => 660, 'alpha2' => 'AI', 'alpha3' => 'AIA', 'name' => 'Anguilla'),
    10  => array('id' => 10 , 'alpha2' => 'AQ', 'alpha3' => 'ATA', 'name' => 'Antarctica'),
    28  => array('id' => 28 , 'alpha2' => 'AG', 'alpha3' => 'ATG', 'name' => 'Antigua and Barbuda'),
    32  => array('id' => 32 , 'alpha2' => 'AR', 'alpha3' => 'ARG', 'name' => 'Argentina'),
    51  => array('id' => 51 , 'alpha2' => 'AM', 'alpha3' => 'ARM', 'name' => 'Armenia'),
    533 => array('id' => 533, 'alpha2' => 'AW', 'alpha3' => 'ABW', 'name' => 'Aruba'),
    36  => array('id' => 36 , 'alpha2' => 'AU', 'alpha3' => 'AUS', 'name' => 'Australia'),
    40  => array('id' => 40 , 'alpha2' => 'AT', 'alpha3' => 'AUT', 'name' => 'Austria'),
    31  => array('id' => 31 , 'alpha2' => 'AZ', 'alpha3' => 'AZE', 'name' => 'Azerbaijan'),
    44  => array('id' => 44 , 'alpha2' => 'BS', 'alpha3' => 'BHS', 'name' => 'Bahamas'),
    48  => array('id' => 48 , 'alpha2' => 'BH', 'alpha3' => 'BHR', 'name' => 'Bahrain'),
    50  => array('id' => 50 , 'alpha2' => 'BD', 'alpha3' => 'BGD', 'name' => 'Bangladesh'),
    52  => array('id' => 52 , 'alpha2' => 'BB', 'alpha3' => 'BRB', 'name' => 'Barbados'),
    112 => array('id' => 112, 'alpha2' => 'BY', 'alpha3' => 'BLR', 'name' => 'Belarus'),
    56  => array('id' => 56 , 'alpha2' => 'BE', 'alpha3' => 'BEL', 'name' => 'Belgium'),
    84  => array('id' => 84 , 'alpha2' => 'BZ', 'alpha3' => 'BLZ', 'name' => 'Belize'),
    204 => array('id' => 204, 'alpha2' => 'BJ', 'alpha3' => 'BEN', 'name' => 'Benin'),
    60  => array('id' => 60 , 'alpha2' => 'BM', 'alpha3' => 'BMU', 'name' => 'Bermuda'),
    64  => array('id' => 64 , 'alpha2' => 'BT', 'alpha3' => 'BTN', 'name' => 'Bhutan'),
    68  => array('id' => 68 , 'alpha2' => 'BO', 'alpha3' => 'BOL', 'name' => 'Bolivia'),
    70  => array('id' => 70 , 'alpha2' => 'BA', 'alpha3' => 'BIH', 'name' => 'Bosnia and Herzegovina'),
    72  => array('id' => 72 , 'alpha2' => 'BW', 'alpha3' => 'BWA', 'name' => 'Botswana'),
    74  => array('id' => 74 , 'alpha2' => 'BV', 'alpha3' => 'BVT', 'name' => 'Bouvet Island'),
    76  => array('id' => 76 , 'alpha2' => 'BR', 'alpha3' => 'BRA', 'name' => 'Brazil'),
    86  => array('id' => 86 , 'alpha2' => 'IO', 'alpha3' => 'IOT', 'name' => 'British Indian Ocean Territory'),
    96  => array('id' => 96 , 'alpha2' => 'BN', 'alpha3' => 'BRN', 'name' => 'Brunei Darussalam'),
    100 => array('id' => 100, 'alpha2' => 'BG', 'alpha3' => 'BGR', 'name' => 'Bulgaria'),
    854 => array('id' => 854, 'alpha2' => 'BF', 'alpha3' => 'BFA', 'name' => 'Burkina Faso'),
    108 => array('id' => 108, 'alpha2' => 'BI', 'alpha3' => 'BDI', 'name' => 'Burundi'),
    116 => array('id' => 116, 'alpha2' => 'KH', 'alpha3' => 'KHM', 'name' => 'Cambodia'),
    120 => array('id' => 120, 'alpha2' => 'CM', 'alpha3' => 'CMR', 'name' => 'Cameroon'),
    124 => array('id' => 124, 'alpha2' => 'CA', 'alpha3' => 'CAN', 'name' => 'Canada'),
    132 => array('id' => 132, 'alpha2' => 'CV', 'alpha3' => 'CPV', 'name' => 'Cabo Verde'),
    535 => array('id' => 535, 'alpha2' => 'BQ', 'alpha3' => 'BES', 'name' => 'Bonaire, Sint Eustatius and Saba'),
    136 => array('id' => 136, 'alpha2' => 'KY', 'alpha3' => 'CYM', 'name' => 'Cayman Islands'),
    140 => array('id' => 140, 'alpha2' => 'CF', 'alpha3' => 'CAF', 'name' => 'Central African Republic'),
    148 => array('id' => 148, 'alpha2' => 'TD', 'alpha3' => 'TCD', 'name' => 'Chad'),
    152 => array('id' => 152, 'alpha2' => 'CL', 'alpha3' => 'CHL', 'name' => 'Chile'),
    156 => array('id' => 156, 'alpha2' => 'CN', 'alpha3' => 'CHN', 'name' => 'China'),
    162 => array('id' => 162, 'alpha2' => 'CX', 'alpha3' => 'CXR', 'name' => 'Christmas Island'),
    166 => array('id' => 166, 'alpha2' => 'CC', 'alpha3' => 'CCK', 'name' => 'Cocos (Keeling) Islands'),
    170 => array('id' => 170, 'alpha2' => 'CO', 'alpha3' => 'COL', 'name' => 'Colombia'),
    174 => array('id' => 174, 'alpha2' => 'KM', 'alpha3' => 'COM', 'name' => 'Comoros'),
    178 => array('id' => 178, 'alpha2' => 'CG', 'alpha3' => 'COG', 'name' => 'Congo'),
    180 => array('id' => 180, 'alpha2' => 'CD', 'alpha3' => 'COD', 'name' => 'Congo (Democratic Republic)'),
    184 => array('id' => 184, 'alpha2' => 'CK', 'alpha3' => 'COK', 'name' => 'Cook Islands'),
    188 => array('id' => 188, 'alpha2' => 'CR', 'alpha3' => 'CRI', 'name' => 'Costa Rica'),
    191 => array('id' => 191, 'alpha2' => 'HR', 'alpha3' => 'HRV', 'name' => 'Croatia'),
    192 => array('id' => 192, 'alpha2' => 'CU', 'alpha3' => 'CUB', 'name' => 'Cuba'),
    531 => array('id' => 531, 'alpha2' => 'CW', 'alpha3' => 'CUW', 'name' => 'Curaçao'),
    196 => array('id' => 196, 'alpha2' => 'CY', 'alpha3' => 'CYP', 'name' => 'Cyprus'),
    203 => array('id' => 203, 'alpha2' => 'CZ', 'alpha3' => 'CZE', 'name' => 'Czechia'),
    208 => array('id' => 208, 'alpha2' => 'DK', 'alpha3' => 'DNK', 'name' => 'Denmark'),
    262 => array('id' => 262, 'alpha2' => 'DJ', 'alpha3' => 'DJI', 'name' => 'Djibouti'),
    212 => array('id' => 212, 'alpha2' => 'DM', 'alpha3' => 'DMA', 'name' => 'Dominica'),
    214 => array('id' => 214, 'alpha2' => 'DO', 'alpha3' => 'DOM', 'name' => 'Dominican Republic'),
    218 => array('id' => 218, 'alpha2' => 'EC', 'alpha3' => 'ECU', 'name' => 'Ecuador'),
    818 => array('id' => 818, 'alpha2' => 'EG', 'alpha3' => 'EGY', 'name' => 'Egypt'),
    222 => array('id' => 222, 'alpha2' => 'SV', 'alpha3' => 'SLV', 'name' => 'El Salvador'),
    226 => array('id' => 226, 'alpha2' => 'GQ', 'alpha3' => 'GNQ', 'name' => 'Equatorial Guinea'),
    232 => array('id' => 232, 'alpha2' => 'ER', 'alpha3' => 'ERI', 'name' => 'Eritrea'),
    233 => array('id' => 233, 'alpha2' => 'EE', 'alpha3' => 'EST', 'name' => 'Estonia'),
    748 => array('id' => 748, 'alpha2' => 'SZ', 'alpha3' => 'SWZ', 'name' => 'Eswatini'),
    231 => array('id' => 231, 'alpha2' => 'ET', 'alpha3' => 'ETH', 'name' => 'Ethiopia'),
    238 => array('id' => 238, 'alpha2' => 'FK', 'alpha3' => 'FLK', 'name' => 'Falkland Islands'),
    234 => array('id' => 234, 'alpha2' => 'FO', 'alpha3' => 'FRO', 'name' => 'Faroe Islands'),
    242 => array('id' => 242, 'alpha2' => 'FJ', 'alpha3' => 'FJI', 'name' => 'Fiji'),
    246 => array('id' => 246, 'alpha2' => 'FI', 'alpha3' => 'FIN', 'name' => 'Finland'),
    250 => array('id' => 250, 'alpha2' => 'FR', 'alpha3' => 'FRA', 'name' => 'France'),
    254 => array('id' => 254, 'alpha2' => 'GF', 'alpha3' => 'GUF', 'name' => 'French Guiana'),
    258 => array('id' => 258, 'alpha2' => 'PF', 'alpha3' => 'PYF', 'name' => 'French Polynesia'),
    260 => array('id' => 260, 'alpha2' => 'TF', 'alpha3' => 'ATF', 'name' => 'French Southern Territories'),
    266 => array('id' => 266, 'alpha2' => 'GA', 'alpha3' => 'GAB', 'name' => 'Gabon'),
    270 => array('id' => 270, 'alpha2' => 'GM', 'alpha3' => 'GMB', 'name' => 'Gambia'),
    268 => array('id' => 268, 'alpha2' => 'GE', 'alpha3' => 'GEO', 'name' => 'Georgia'),
    276 => array('id' => 276, 'alpha2' => 'DE', 'alpha3' => 'DEU', 'name' => 'Germany'),
    288 => array('id' => 288, 'alpha2' => 'GH', 'alpha3' => 'GHA', 'name' => 'Ghana'),
    292 => array('id' => 292, 'alpha2' => 'GI', 'alpha3' => 'GIB', 'name' => 'Gibraltar'),
    300 => array('id' => 300, 'alpha2' => 'GR', 'alpha3' => 'GRC', 'name' => 'Greece'),
    304 => array('id' => 304, 'alpha2' => 'GL', 'alpha3' => 'GRL', 'name' => 'Greenland'),
    308 => array('id' => 308, 'alpha2' => 'GD', 'alpha3' => 'GRD', 'name' => 'Grenada'),
    312 => array('id' => 312, 'alpha2' => 'GP', 'alpha3' => 'GLP', 'name' => 'Guadeloupe'),
    316 => array('id' => 316, 'alpha2' => 'GU', 'alpha3' => 'GUM', 'name' => 'Guam'),
    320 => array('id' => 320, 'alpha2' => 'GT', 'alpha3' => 'GTM', 'name' => 'Guatemala'),
    831 => array('id' => 831, 'alpha2' => 'GG', 'alpha3' => 'GGY', 'name' => 'Guernsey'),
    324 => array('id' => 324, 'alpha2' => 'GN', 'alpha3' => 'GIN', 'name' => 'Guinea'),
    624 => array('id' => 624, 'alpha2' => 'GW', 'alpha3' => 'GNB', 'name' => 'Guinea-Bissau'),
    328 => array('id' => 328, 'alpha2' => 'GY', 'alpha3' => 'GUY', 'name' => 'Guyana'),
    332 => array('id' => 332, 'alpha2' => 'HT', 'alpha3' => 'HTI', 'name' => 'Haiti'),
    334 => array('id' => 334, 'alpha2' => 'HM', 'alpha3' => 'HMD', 'name' => 'Heard Island and McDonald Islands'),
    340 => array('id' => 340, 'alpha2' => 'HN', 'alpha3' => 'HND', 'name' => 'Honduras'),
    344 => array('id' => 344, 'alpha2' => 'HK', 'alpha3' => 'HKG', 'name' => 'Hong Kong'),
    348 => array('id' => 348, 'alpha2' => 'HU', 'alpha3' => 'HUN', 'name' => 'Hungary'),
    352 => array('id' => 352, 'alpha2' => 'IS', 'alpha3' => 'ISL', 'name' => 'Iceland'),
    356 => array('id' => 356, 'alpha2' => 'IN', 'alpha3' => 'IND', 'name' => 'India'),
    360 => array('id' => 360, 'alpha2' => 'ID', 'alpha3' => 'IDN', 'name' => 'Indonesia'),
    364 => array('id' => 364, 'alpha2' => 'IR', 'alpha3' => 'IRN', 'name' => 'Iran'),
    368 => array('id' => 368, 'alpha2' => 'IQ', 'alpha3' => 'IRQ', 'name' => 'Iraq'),
    372 => array('id' => 372, 'alpha2' => 'IE', 'alpha3' => 'IRL', 'name' => 'Ireland'),
    833 => array('id' => 833, 'alpha2' => 'IM', 'alpha3' => 'IMN', 'name' => 'Isle of Man'),
    376 => array('id' => 376, 'alpha2' => 'IL', 'alpha3' => 'ISR', 'name' => 'Israel'),
    380 => array('id' => 380, 'alpha2' => 'IT', 'alpha3' => 'ITA', 'name' => 'Italy'),
    384 => array('id' => 384, 'alpha2' => 'CI', 'alpha3' => 'CIV', 'name' => 'Côte d'Ivoire'),
    388 => array('id' => 388, 'alpha2' => 'JM', 'alpha3' => 'JAM', 'name' => 'Jamaica'),
    392 => array('id' => 392, 'alpha2' => 'JP', 'alpha3' => 'JPN', 'name' => 'Japan'),
    832 => array('id' => 832, 'alpha2' => 'JE', 'alpha3' => 'JEY', 'name' => 'Jersey'),
    400 => array('id' => 400, 'alpha2' => 'JO', 'alpha3' => 'JOR', 'name' => 'Jordan'),
    398 => array('id' => 398, 'alpha2' => 'KZ', 'alpha3' => 'KAZ', 'name' => 'Kazakhstan'),
    404 => array('id' => 404, 'alpha2' => 'KE', 'alpha3' => 'KEN', 'name' => 'Kenya'),
    296 => array('id' => 296, 'alpha2' => 'KI', 'alpha3' => 'KIR', 'name' => 'Kiribati'),
    414 => array('id' => 414, 'alpha2' => 'KW', 'alpha3' => 'KWT', 'name' => 'Kuwait'),
    417 => array('id' => 417, 'alpha2' => 'KG', 'alpha3' => 'KGZ', 'name' => 'Kyrgyzstan'),
    418 => array('id' => 418, 'alpha2' => 'LA', 'alpha3' => 'LAO', 'name' => 'Lao People's Democratic Republic'),
    428 => array('id' => 428, 'alpha2' => 'LV', 'alpha3' => 'LVA', 'name' => 'Latvia'),
    422 => array('id' => 422, 'alpha2' => 'LB', 'alpha3' => 'LBN', 'name' => 'Lebanon'),
    426 => array('id' => 426, 'alpha2' => 'LS', 'alpha3' => 'LSO', 'name' => 'Lesotho'),
    430 => array('id' => 430, 'alpha2' => 'LR', 'alpha3' => 'LBR', 'name' => 'Liberia'),
    434 => array('id' => 434, 'alpha2' => 'LY', 'alpha3' => 'LBY', 'name' => 'Libya'),
    438 => array('id' => 438, 'alpha2' => 'LI', 'alpha3' => 'LIE', 'name' => 'Liechtenstein'),
    440 => array('id' => 440, 'alpha2' => 'LT', 'alpha3' => 'LTU', 'name' => 'Lithuania'),
    442 => array('id' => 442, 'alpha2' => 'LU', 'alpha3' => 'LUX', 'name' => 'Luxembourg'),
    446 => array('id' => 446, 'alpha2' => 'MO', 'alpha3' => 'MAC', 'name' => 'Macao'),
    450 => array('id' => 450, 'alpha2' => 'MG', 'alpha3' => 'MDG', 'name' => 'Madagascar'),
    454 => array('id' => 454, 'alpha2' => 'MW', 'alpha3' => 'MWI', 'name' => 'Malawi'),
    458 => array('id' => 458, 'alpha2' => 'MY', 'alpha3' => 'MYS', 'name' => 'Malaysia'),
    462 => array('id' => 462, 'alpha2' => 'MV', 'alpha3' => 'MDV', 'name' => 'Maldives'),
    466 => array('id' => 466, 'alpha2' => 'ML', 'alpha3' => 'MLI', 'name' => 'Mali'),
    470 => array('id' => 470, 'alpha2' => 'MT', 'alpha3' => 'MLT', 'name' => 'Malta'),
    584 => array('id' => 584, 'alpha2' => 'MH', 'alpha3' => 'MHL', 'name' => 'Marshall Islands'),
    474 => array('id' => 474, 'alpha2' => 'MQ', 'alpha3' => 'MTQ', 'name' => 'Martinique'),
    478 => array('id' => 478, 'alpha2' => 'MR', 'alpha3' => 'MRT', 'name' => 'Mauritania'),
    480 => array('id' => 480, 'alpha2' => 'MU', 'alpha3' => 'MUS', 'name' => 'Mauritius'),
    175 => array('id' => 175, 'alpha2' => 'YT', 'alpha3' => 'MYT', 'name' => 'Mayotte'),
    484 => array('id' => 484, 'alpha2' => 'MX', 'alpha3' => 'MEX', 'name' => 'Mexico'),
    583 => array('id' => 583, 'alpha2' => 'FM', 'alpha3' => 'FSM', 'name' => 'Micronesia'),
    498 => array('id' => 498, 'alpha2' => 'MD', 'alpha3' => 'MDA', 'name' => 'Moldova'),
    492 => array('id' => 492, 'alpha2' => 'MC', 'alpha3' => 'MCO', 'name' => 'Monaco'),
    496 => array('id' => 496, 'alpha2' => 'MN', 'alpha3' => 'MNG', 'name' => 'Mongolia'),
    499 => array('id' => 499, 'alpha2' => 'ME', 'alpha3' => 'MNE', 'name' => 'Montenegro'),
    500 => array('id' => 500, 'alpha2' => 'MS', 'alpha3' => 'MSR', 'name' => 'Montserrat'),
    504 => array('id' => 504, 'alpha2' => 'MA', 'alpha3' => 'MAR', 'name' => 'Morocco'),
    508 => array('id' => 508, 'alpha2' => 'MZ', 'alpha3' => 'MOZ', 'name' => 'Mozambique'),
    104 => array('id' => 104, 'alpha2' => 'MM', 'alpha3' => 'MMR', 'name' => 'Myanmar'),
    516 => array('id' => 516, 'alpha2' => 'NA', 'alpha3' => 'NAM', 'name' => 'Namibia'),
    520 => array('id' => 520, 'alpha2' => 'NR', 'alpha3' => 'NRU', 'name' => 'Nauru'),
    524 => array('id' => 524, 'alpha2' => 'NP', 'alpha3' => 'NPL', 'name' => 'Nepal'),
    528 => array('id' => 528, 'alpha2' => 'NL', 'alpha3' => 'NLD', 'name' => 'Netherlands'),
    540 => array('id' => 540, 'alpha2' => 'NC', 'alpha3' => 'NCL', 'name' => 'New Caledonia'),
    554 => array('id' => 554, 'alpha2' => 'NZ', 'alpha3' => 'NZL', 'name' => 'New Zealand'),
    558 => array('id' => 558, 'alpha2' => 'NI', 'alpha3' => 'NIC', 'name' => 'Nicaragua'),
    562 => array('id' => 562, 'alpha2' => 'NE', 'alpha3' => 'NER', 'name' => 'Niger'),
    566 => array('id' => 566, 'alpha2' => 'NG', 'alpha3' => 'NGA', 'name' => 'Nigeria'),
    570 => array('id' => 570, 'alpha2' => 'NU', 'alpha3' => 'NIU', 'name' => 'Niue'),
    574 => array('id' => 574, 'alpha2' => 'NF', 'alpha3' => 'NFK', 'name' => 'Norfolk Island'),
    408 => array('id' => 408, 'alpha2' => 'KP', 'alpha3' => 'PRK', 'name' => 'Korea (Democratic People's Republic)'),
    807 => array('id' => 807, 'alpha2' => 'MK', 'alpha3' => 'MKD', 'name' => 'North Macedonia'),
    580 => array('id' => 580, 'alpha2' => 'MP', 'alpha3' => 'MNP', 'name' => 'Northern Mariana Islands'),
    578 => array('id' => 578, 'alpha2' => 'NO', 'alpha3' => 'NOR', 'name' => 'Norway'),
    512 => array('id' => 512, 'alpha2' => 'OM', 'alpha3' => 'OMN', 'name' => 'Oman'),
    586 => array('id' => 586, 'alpha2' => 'PK', 'alpha3' => 'PAK', 'name' => 'Pakistan'),
    585 => array('id' => 585, 'alpha2' => 'PW', 'alpha3' => 'PLW', 'name' => 'Palau'),
    275 => array('id' => 275, 'alpha2' => 'PS', 'alpha3' => 'PSE', 'name' => 'Palestine'),
    591 => array('id' => 591, 'alpha2' => 'PA', 'alpha3' => 'PAN', 'name' => 'Panama'),
    598 => array('id' => 598, 'alpha2' => 'PG', 'alpha3' => 'PNG', 'name' => 'Papua New Guinea'),
    600 => array('id' => 600, 'alpha2' => 'PY', 'alpha3' => 'PRY', 'name' => 'Paraguay'),
    604 => array('id' => 604, 'alpha2' => 'PE', 'alpha3' => 'PER', 'name' => 'Peru'),
    608 => array('id' => 608, 'alpha2' => 'PH', 'alpha3' => 'PHL', 'name' => 'Philippines'),
    612 => array('id' => 612, 'alpha2' => 'PN', 'alpha3' => 'PCN', 'name' => 'Pitcairn'),
    616 => array('id' => 616, 'alpha2' => 'PL', 'alpha3' => 'POL', 'name' => 'Poland'),
    620 => array('id' => 620, 'alpha2' => 'PT', 'alpha3' => 'PRT', 'name' => 'Portugal'),
    630 => array('id' => 630, 'alpha2' => 'PR', 'alpha3' => 'PRI', 'name' => 'Puerto Rico'),
    634 => array('id' => 634, 'alpha2' => 'QA', 'alpha3' => 'QAT', 'name' => 'Qatar'),
    638 => array('id' => 638, 'alpha2' => 'RE', 'alpha3' => 'REU', 'name' => 'Réunion'),
    642 => array('id' => 642, 'alpha2' => 'RO', 'alpha3' => 'ROU', 'name' => 'Romania'),
    643 => array('id' => 643, 'alpha2' => 'RU', 'alpha3' => 'RUS', 'name' => 'Russian Federation'),
    646 => array('id' => 646, 'alpha2' => 'RW', 'alpha3' => 'RWA', 'name' => 'Rwanda'),
    652 => array('id' => 652, 'alpha2' => 'BL', 'alpha3' => 'BLM', 'name' => 'Saint Barthélemy'),
    654 => array('id' => 654, 'alpha2' => 'SH', 'alpha3' => 'SHN', 'name' => 'Saint Helena, Ascension and Tristan da Cunha'),
    659 => array('id' => 659, 'alpha2' => 'KN', 'alpha3' => 'KNA', 'name' => 'Saint Kitts and Nevis'),
    662 => array('id' => 662, 'alpha2' => 'LC', 'alpha3' => 'LCA', 'name' => 'Saint Lucia'),
    663 => array('id' => 663, 'alpha2' => 'MF', 'alpha3' => 'MAF', 'name' => 'Saint Martin (French part)'),
    666 => array('id' => 666, 'alpha2' => 'PM', 'alpha3' => 'SPM', 'name' => 'Saint Pierre and Miquelon'),
    670 => array('id' => 670, 'alpha2' => 'VC', 'alpha3' => 'VCT', 'name' => 'Saint Vincent and the Grenadines'),
    882 => array('id' => 882, 'alpha2' => 'WS', 'alpha3' => 'WSM', 'name' => 'Samoa'),
    674 => array('id' => 674, 'alpha2' => 'SM', 'alpha3' => 'SMR', 'name' => 'San Marino'),
    678 => array('id' => 678, 'alpha2' => 'ST', 'alpha3' => 'STP', 'name' => 'Sao Tome and Principe'),
    682 => array('id' => 682, 'alpha2' => 'SA', 'alpha3' => 'SAU', 'name' => 'Saudi Arabia'),
    686 => array('id' => 686, 'alpha2' => 'SN', 'alpha3' => 'SEN', 'name' => 'Senegal'),
    688 => array('id' => 688, 'alpha2' => 'RS', 'alpha3' => 'SRB', 'name' => 'Serbia'),
    690 => array('id' => 690, 'alpha2' => 'SC', 'alpha3' => 'SYC', 'name' => 'Seychelles'),
    694 => array('id' => 694, 'alpha2' => 'SL', 'alpha3' => 'SLE', 'name' => 'Sierra Leone'),
    702 => array('id' => 702, 'alpha2' => 'SG', 'alpha3' => 'SGP', 'name' => 'Singapore'),
    534 => array('id' => 534, 'alpha2' => 'SX', 'alpha3' => 'SXM', 'name' => 'Sint Maarten (Dutch part)'),
    703 => array('id' => 703, 'alpha2' => 'SK', 'alpha3' => 'SVK', 'name' => 'Slovakia'),
    705 => array('id' => 705, 'alpha2' => 'SI', 'alpha3' => 'SVN', 'name' => 'Slovenia'),
    90  => array('id' => 90 , 'alpha2' => 'SB', 'alpha3' => 'SLB', 'name' => 'Solomon Islands'),
    706 => array('id' => 706, 'alpha2' => 'SO', 'alpha3' => 'SOM', 'name' => 'Somalia'),
    710 => array('id' => 710, 'alpha2' => 'ZA', 'alpha3' => 'ZAF', 'name' => 'South Africa'),
    239 => array('id' => 239, 'alpha2' => 'GS', 'alpha3' => 'SGS', 'name' => 'South Georgia and the South Sandwich Islands'),
    410 => array('id' => 410, 'alpha2' => 'KR', 'alpha3' => 'KOR', 'name' => 'Korea (Republic)'),
    728 => array('id' => 728, 'alpha2' => 'SS', 'alpha3' => 'SSD', 'name' => 'South Sudan'),
    724 => array('id' => 724, 'alpha2' => 'ES', 'alpha3' => 'ESP', 'name' => 'Spain'),
    144 => array('id' => 144, 'alpha2' => 'LK', 'alpha3' => 'LKA', 'name' => 'Sri Lanka'),
    729 => array('id' => 729, 'alpha2' => 'SD', 'alpha3' => 'SDN', 'name' => 'Sudan'),
    740 => array('id' => 740, 'alpha2' => 'SR', 'alpha3' => 'SUR', 'name' => 'Suriname'),
    744 => array('id' => 744, 'alpha2' => 'SJ', 'alpha3' => 'SJM', 'name' => 'Svalbard and Jan Mayen'),
    752 => array('id' => 752, 'alpha2' => 'SE', 'alpha3' => 'SWE', 'name' => 'Sweden'),
    756 => array('id' => 756, 'alpha2' => 'CH', 'alpha3' => 'CHE', 'name' => 'Switzerland'),
    760 => array('id' => 760, 'alpha2' => 'SY', 'alpha3' => 'SYR', 'name' => 'Syrian Arab Republic'),
    158 => array('id' => 158, 'alpha2' => 'TW', 'alpha3' => 'TWN', 'name' => 'Taiwan'),
    762 => array('id' => 762, 'alpha2' => 'TJ', 'alpha3' => 'TJK', 'name' => 'Tajikistan'),
    834 => array('id' => 834, 'alpha2' => 'TZ', 'alpha3' => 'TZA', 'name' => 'Tanzania'),
    764 => array('id' => 764, 'alpha2' => 'TH', 'alpha3' => 'THA', 'name' => 'Thailand'),
    626 => array('id' => 626, 'alpha2' => 'TL', 'alpha3' => 'TLS', 'name' => 'Timor-Leste'),
    768 => array('id' => 768, 'alpha2' => 'TG', 'alpha3' => 'TGO', 'name' => 'Togo'),
    772 => array('id' => 772, 'alpha2' => 'TK', 'alpha3' => 'TKL', 'name' => 'Tokelau'),
    776 => array('id' => 776, 'alpha2' => 'TO', 'alpha3' => 'TON', 'name' => 'Tonga'),
    780 => array('id' => 780, 'alpha2' => 'TT', 'alpha3' => 'TTO', 'name' => 'Trinidad and Tobago'),
    788 => array('id' => 788, 'alpha2' => 'TN', 'alpha3' => 'TUN', 'name' => 'Tunisia'),
    792 => array('id' => 792, 'alpha2' => 'TR', 'alpha3' => 'TUR', 'name' => 'Türkiye'),
    795 => array('id' => 795, 'alpha2' => 'TM', 'alpha3' => 'TKM', 'name' => 'Turkmenistan'),
    796 => array('id' => 796, 'alpha2' => 'TC', 'alpha3' => 'TCA', 'name' => 'Turks and Caicos Islands'),
    798 => array('id' => 798, 'alpha2' => 'TV', 'alpha3' => 'TUV', 'name' => 'Tuvalu'),
    581 => array('id' => 581, 'alpha2' => 'UM', 'alpha3' => 'UMI', 'name' => 'United States Minor Outlying Islands'),
    800 => array('id' => 800, 'alpha2' => 'UG', 'alpha3' => 'UGA', 'name' => 'Uganda'),
    804 => array('id' => 804, 'alpha2' => 'UA', 'alpha3' => 'UKR', 'name' => 'Ukraine'),
    784 => array('id' => 784, 'alpha2' => 'AE', 'alpha3' => 'ARE', 'name' => 'United Arab Emirates'),
    826 => array('id' => 826, 'alpha2' => 'GB', 'alpha3' => 'GBR', 'name' => 'United Kingdom of Great Britain and Northern Ireland'),
    840 => array('id' => 840, 'alpha2' => 'US', 'alpha3' => 'USA', 'name' => 'United States of America'),
    858 => array('id' => 858, 'alpha2' => 'UY', 'alpha3' => 'URY', 'name' => 'Uruguay'),
    860 => array('id' => 860, 'alpha2' => 'UZ', 'alpha3' => 'UZB', 'name' => 'Uzbekistan'),
    548 => array('id' => 548, 'alpha2' => 'VU', 'alpha3' => 'VUT', 'name' => 'Vanuatu'),
    336 => array('id' => 336, 'alpha2' => 'VA', 'alpha3' => 'VAT', 'name' => 'Holy See'),
    862 => array('id' => 862, 'alpha2' => 'VE', 'alpha3' => 'VEN', 'name' => 'Venezuela'),
    704 => array('id' => 704, 'alpha2' => 'VN', 'alpha3' => 'VNM', 'name' => 'Viet Nam'),
    92  => array('id' => 92 , 'alpha2' => 'VG', 'alpha3' => 'VGB', 'name' => 'Virgin Islands (British)'),
    850 => array('id' => 850, 'alpha2' => 'VI', 'alpha3' => 'VIR', 'name' => 'Virgin Islands (U.S.)'),
    876 => array('id' => 876, 'alpha2' => 'WF', 'alpha3' => 'WLF', 'name' => 'Wallis and Futuna'),
    732 => array('id' => 732, 'alpha2' => 'EH', 'alpha3' => 'ESH', 'name' => 'Western Sahara'),
    887 => array('id' => 887, 'alpha2' => 'YE', 'alpha3' => 'YEM', 'name' => 'Yemen'),
    894 => array('id' => 894, 'alpha2' => 'ZM', 'alpha3' => 'ZMB', 'name' => 'Zambia'),
    716 => array('id' => 716, 'alpha2' => 'ZW', 'alpha3' => 'ZWE', 'name' => 'Zimbabwe'),
);
